/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LinuxDateFormat.java
 *
 * Created on 1 sept. 2010, 13:50:29
 */

package net.atomique.ksar.UI;

import java.util.Arrays;

import javax.swing.DefaultComboBoxModel;

import net.atomique.ksar.Parser.Linux;

/**
 *
 * @author alex
 */
public class LinuxDateFormat extends javax.swing.JDialog {

	/** Creates new form LinuxDateFormat */
	public LinuxDateFormat(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		load_linuxformat();
		pack();
		setLocationRelativeTo(parent);
		toFront();
		setVisible(true);

	}

	private void load_linuxformat() {
		Arrays.stream(Linux.DateFormat.values()).forEach(e -> LinuxFormatComboModel.addElement(e));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jPanel4 = new javax.swing.JPanel();
		jCheckBox1 = new javax.swing.JCheckBox();
		jPanel2 = new javax.swing.JPanel();
		OkButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

		jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		jLabel1.setLabelFor(jComboBox1);
		jLabel1.setText("Select date format:");
		jPanel3.add(jLabel1);

		jComboBox1.setModel(LinuxFormatComboModel);
		jComboBox1.setPreferredSize(new java.awt.Dimension(300, 27));
		jPanel3.add(jComboBox1);

		jPanel1.add(jPanel3);

		jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		jCheckBox1.setText("Always use this format");
		jPanel4.add(jCheckBox1);

		jPanel1.add(jPanel4);

		getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

		OkButton.setText("Ok");
		OkButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				OkButtonActionPerformed(evt);
			}
		});
		jPanel2.add(OkButton);

		getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_OkButtonActionPerformed
		this.dispose();
		ok_to_proceed = true;
	}// GEN-LAST:event_OkButtonActionPerformed

	public boolean hasToRemenber() {
		return jCheckBox1.isSelected();
	}

	public Linux.DateFormat getDateFormat() {
		return jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
	}

	public boolean isOk() {
		return ok_to_proceed;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton OkButton;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JComboBox<Linux.DateFormat> jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	// End of variables declaration//GEN-END:variables

	DefaultComboBoxModel<Linux.DateFormat> LinuxFormatComboModel = new DefaultComboBoxModel<>();
	boolean ok_to_proceed = false;
}
