/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SSHDialog.java
 *
 * Created on 11 août 2010, 15:34:23
 */

package net.atomique.ksar.UI;

/**
 *
 * @author Max
 */
public class SSHDialog extends javax.swing.JInternalFrame {

    /** Creates new form SSHDialog */
    public SSHDialog() {
        initComponents();
        System.out.println("shown");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerpanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        infopanel = new javax.swing.JPanel();
        hostnamePanel = new javax.swing.JPanel();
        HostnameLabel = new javax.swing.JLabel();
        HostnameField = new javax.swing.JTextField();
        userPanel = new javax.swing.JPanel();
        UsernameLabel = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        passwordPanel = new javax.swing.JPanel();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        ComboBoxLabel = new javax.swing.JLabel();
        commandComboBox = new javax.swing.JComboBox();
        buttonpanel = new javax.swing.JPanel();
        Cancelbutton = new javax.swing.JButton();
        ConnectionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleLabel.setText("SSH Connection");
        headerpanel.add(titleLabel);

        getContentPane().add(headerpanel, java.awt.BorderLayout.PAGE_START);

        infopanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        infopanel.setLayout(new javax.swing.BoxLayout(infopanel, javax.swing.BoxLayout.PAGE_AXIS));

        hostnamePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        HostnameLabel.setText("Hostname");
        hostnamePanel.add(HostnameLabel);

        HostnameField.setMinimumSize(new java.awt.Dimension(150, 20));
        HostnameField.setPreferredSize(new java.awt.Dimension(180, 20));
        hostnamePanel.add(HostnameField);

        infopanel.add(hostnamePanel);

        userPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        UsernameLabel.setText("Username");
        userPanel.add(UsernameLabel);

        UsernameField.setPreferredSize(new java.awt.Dimension(120, 20));
        userPanel.add(UsernameField);

        infopanel.add(userPanel);

        passwordPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        PasswordLabel.setText("Password");
        passwordPanel.add(PasswordLabel);

        PasswordField.setMinimumSize(new java.awt.Dimension(100, 20));
        PasswordField.setPreferredSize(new java.awt.Dimension(120, 20));
        passwordPanel.add(PasswordField);

        infopanel.add(passwordPanel);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        ComboBoxLabel.setText("Command");
        jPanel1.add(ComboBoxLabel);

        commandComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        commandComboBox.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel1.add(commandComboBox);

        infopanel.add(jPanel1);

        getContentPane().add(infopanel, java.awt.BorderLayout.CENTER);

        Cancelbutton.setText("Cancel");
        Cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbuttonActionPerformed(evt);
            }
        });
        buttonpanel.add(Cancelbutton);

        ConnectionButton.setText("Connection");
        ConnectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectionButtonActionPerformed(evt);
            }
        });
        buttonpanel.add(ConnectionButton);

        getContentPane().add(buttonpanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbuttonActionPerformed
        this.dispose();
}//GEN-LAST:event_CancelbuttonActionPerformed

    private void ConnectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectionButtonActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ConnectionButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelbutton;
    private javax.swing.JLabel ComboBoxLabel;
    private javax.swing.JButton ConnectionButton;
    private javax.swing.JTextField HostnameField;
    private javax.swing.JLabel HostnameLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JPanel buttonpanel;
    private javax.swing.JComboBox commandComboBox;
    private javax.swing.JPanel headerpanel;
    private javax.swing.JPanel hostnamePanel;
    private javax.swing.JPanel infopanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables

}
